// Shared currency dictionary — shortcode → metadata
const CURRENCIES = {
  AED: { symbol: ["د.إ", "AED"], flag: "🇦🇪", name: "UAE Dirham", decimals: 2 },
  AFN: {
    symbol: ["؋", "AFN"],
    flag: "🇦🇫",
    name: "Afghan Afghani",
    decimals: 2,
  },
  ALL: { symbol: ["L", "ALL"], flag: "🇦🇱", name: "Albanian Lek", decimals: 2 },
  AMD: { symbol: ["֏", "AMD"], flag: "🇦🇲", name: "Armenian Dram", decimals: 2 },
  ANG: {
    symbol: ["ƒ", "ANG"],
    flag: "🇨🇼",
    name: "Netherlands Antillean Guilder",
    decimals: 2,
  },
  AOA: {
    symbol: ["Kz", "AOA"],
    flag: "🇦🇴",
    name: "Angolan Kwanza",
    decimals: 2,
  },
  ARS: {
    symbol: ["$", "ARS"],
    flag: "🇦🇷",
    name: "Argentine Peso",
    decimals: 2,
  },
  AUD: {
    symbol: ["A$", "AUD"],
    flag: "🇦🇺",
    name: "Australian Dollar",
    decimals: 2,
  },
  AWG: { symbol: ["ƒ", "AWG"], flag: "🇦🇼", name: "Aruban Florin", decimals: 2 },
  AZN: {
    symbol: ["₼", "AZN"],
    flag: "🇦🇿",
    name: "Azerbaijani Manat",
    decimals: 2,
  },
  BAM: {
    symbol: ["KM", "BAM"],
    flag: "🇧🇦",
    name: "Bosnia-Herzegovina Convertible Mark",
    decimals: 2,
  },
  BBD: {
    symbol: ["$", "BBD"],
    flag: "🇧🇧",
    name: "Barbadian Dollar",
    decimals: 2,
  },
  BDT: {
    symbol: ["৳", "BDT"],
    flag: "🇧🇩",
    name: "Bangladeshi Taka",
    decimals: 0,
  },
  BHD: {
    symbol: ["د.ب", "BHD"],
    flag: "🇧🇭",
    name: "Bahraini Dinar",
    decimals: 3,
  },
  BIF: {
    symbol: ["FBu", "BIF"],
    flag: "🇧🇮",
    name: "Burundian Franc",
    decimals: 0,
  },
  BMD: {
    symbol: ["$", "BMD"],
    flag: "🇧🇲",
    name: "Bermudian Dollar",
    decimals: 2,
  },
  BND: { symbol: ["$", "BND"], flag: "🇧🇳", name: "Brunei Dollar", decimals: 2 },
  BOB: {
    symbol: ["Bs.", "BOB"],
    flag: "🇧🇴",
    name: "Bolivian Boliviano",
    decimals: 2,
  },
  BRL: {
    symbol: ["R$", "BRL"],
    flag: "🇧🇷",
    name: "Brazilian Real",
    decimals: 2,
  },
  BSD: {
    symbol: ["$", "BSD"],
    flag: "🇧🇸",
    name: "Bahamian Dollar",
    decimals: 2,
  },
  BTN: {
    symbol: ["Nu.", "BTN"],
    flag: "🇧🇹",
    name: "Bhutanese Ngultrum",
    decimals: 2,
  },
  BWP: { symbol: ["P", "BWP"], flag: "🇧🇼", name: "Botswana Pula", decimals: 2 },
  BYN: {
    symbol: ["Br", "BYN"],
    flag: "🇧🇾",
    name: "Belarusian Ruble",
    decimals: 2,
  },
  BZD: { symbol: ["$", "BZD"], flag: "🇧🇿", name: "Belize Dollar", decimals: 2 },
  CAD: {
    symbol: ["C$", "CAD"],
    flag: "🇨🇦",
    name: "Canadian Dollar",
    decimals: 2,
  },
  CDF: {
    symbol: ["FC", "CDF"],
    flag: "🇨🇩",
    name: "Congolese Franc",
    decimals: 2,
  },
  CHF: { symbol: ["CHF", "CHF"], flag: "🇨🇭", name: "Swiss Franc", decimals: 2 },
  CLP: { symbol: ["$", "CLP"], flag: "🇨🇱", name: "Chilean Peso", decimals: 0 },
  CNH: {
    symbol: ["¥", "CNH"],
    flag: "🇨🇳",
    name: "Chinese Yuan (Offshore)",
    decimals: 2,
  },
  CNY: {
    symbol: ["¥", "CNY"],
    flag: "🇨🇳",
    name: "Chinese Yuan Renminbi",
    decimals: 2,
  },
  COP: {
    symbol: ["$", "COP"],
    flag: "🇨🇴",
    name: "Colombian Peso",
    decimals: 2,
  },
  CRC: {
    symbol: ["₡", "CRC"],
    flag: "🇨🇷",
    name: "Costa Rican Colón",
    decimals: 2,
  },
  CUP: { symbol: ["$", "CUP"], flag: "🇨🇺", name: "Cuban Peso", decimals: 2 },
  CVE: {
    symbol: ["$", "CVE"],
    flag: "🇨🇻",
    name: "Cape Verdean Escudo",
    decimals: 2,
  },
  CZK: { symbol: ["Kč", "CZK"], flag: "🇨🇿", name: "Czech Koruna", decimals: 2 },
  DJF: {
    symbol: ["Fdj", "DJF"],
    flag: "🇩🇯",
    name: "Djiboutian Franc",
    decimals: 0,
  },
  DKK: { symbol: ["kr", "DKK"], flag: "🇩🇰", name: "Danish Krone", decimals: 2 },
  DOP: {
    symbol: ["$", "DOP"],
    flag: "🇩🇴",
    name: "Dominican Peso",
    decimals: 2,
  },
  DZD: {
    symbol: ["د.ج", "DZD"],
    flag: "🇩🇿",
    name: "Algerian Dinar",
    decimals: 2,
  },
  EGP: {
    symbol: ["£", "EGP"],
    flag: "🇪🇬",
    name: "Egyptian Pound",
    decimals: 2,
  },
  ERN: {
    symbol: ["Nfk", "ERN"],
    flag: "🇪🇷",
    name: "Eritrean Nakfa",
    decimals: 2,
  },
  ETB: {
    symbol: ["Br", "ETB"],
    flag: "🇪🇹",
    name: "Ethiopian Birr",
    decimals: 2,
  },
  EUR: { symbol: ["€", "EUR"], flag: "🇪🇺", name: "Euro", decimals: 2 },
  FJD: { symbol: ["$", "FJD"], flag: "🇫🇯", name: "Fijian Dollar", decimals: 2 },
  FKP: {
    symbol: ["£", "FKP"],
    flag: "🇫🇰",
    name: "Falkland Islands Pound",
    decimals: 2,
  },
  GBP: { symbol: ["£", "GBP"], flag: "🇬🇧", name: "British Pound", decimals: 2 },
  GEL: { symbol: ["₾", "GEL"], flag: "🇬🇪", name: "Georgian Lari", decimals: 2 },
  GGP: {
    symbol: ["£", "GGP"],
    flag: "🇬🇬",
    name: "Guernsey Pound",
    decimals: 2,
  },
  GHS: { symbol: ["₵", "GHS"], flag: "🇬🇭", name: "Ghanaian Cedi", decimals: 2 },
  GIP: {
    symbol: ["£", "GIP"],
    flag: "🇬🇮",
    name: "Gibraltar Pound",
    decimals: 2,
  },
  GMD: {
    symbol: ["D", "GMD"],
    flag: "🇬🇲",
    name: "Gambian Dalasi",
    decimals: 2,
  },
  GNF: {
    symbol: ["FG", "GNF"],
    flag: "🇬🇳",
    name: "Guinean Franc",
    decimals: 0,
  },
  GTQ: {
    symbol: ["Q", "GTQ"],
    flag: "🇬🇹",
    name: "Guatemalan Quetzal",
    decimals: 2,
  },
  GYD: {
    symbol: ["$", "GYD"],
    flag: "🇬🇾",
    name: "Guyanese Dollar",
    decimals: 2,
  },
  HKD: {
    symbol: ["$", "HKD"],
    flag: "🇭🇰",
    name: "Hong Kong Dollar",
    decimals: 2,
  },
  HNL: {
    symbol: ["L", "HNL"],
    flag: "🇭🇳",
    name: "Honduran Lempira",
    decimals: 2,
  },
  HTG: {
    symbol: ["G", "HTG"],
    flag: "🇭🇹",
    name: "Haitian Gourde",
    decimals: 2,
  },
  HUF: {
    symbol: ["Ft", "HUF"],
    flag: "🇭🇺",
    name: "Hungarian Forint",
    decimals: 2,
  },
  IDR: {
    symbol: ["Rp", "IDR"],
    flag: "🇮🇩",
    name: "Indonesian Rupiah",
    decimals: 2,
  },
  ILS: {
    symbol: ["₪", "ILS"],
    flag: "🇮🇱",
    name: "Israeli New Shekel",
    decimals: 2,
  },
  IMP: {
    symbol: ["£", "IMP"],
    flag: "🇮🇲",
    name: "Isle of Man Pound",
    decimals: 2,
  },
  INR: { symbol: ["₹", "INR"], flag: "🇮🇳", name: "Indian Rupee", decimals: 0 },
  IQD: { symbol: ["ع.د", "IQD"], flag: "🇮🇶", name: "Iraqi Dinar", decimals: 3 },
  IRR: { symbol: ["﷼", "IRR"], flag: "🇮🇷", name: "Iranian Rial", decimals: 2 },
  ISK: {
    symbol: ["kr", "ISK"],
    flag: "🇮🇸",
    name: "Icelandic Króna",
    decimals: 0,
  },
  JEP: { symbol: ["£", "JEP"], flag: "🇯🇪", name: "Jersey Pound", decimals: 2 },
  JMD: {
    symbol: ["$", "JMD"],
    flag: "🇯🇲",
    name: "Jamaican Dollar",
    decimals: 2,
  },
  JOD: {
    symbol: ["د.ا", "JOD"],
    flag: "🇯🇴",
    name: "Jordanian Dinar",
    decimals: 3,
  },
  JPY: { symbol: ["¥", "JPY"], flag: "🇯🇵", name: "Japanese Yen", decimals: 0 },
  KES: {
    symbol: ["KSh", "KES"],
    flag: "🇰🇪",
    name: "Kenyan Shilling",
    decimals: 2,
  },
  KGS: {
    symbol: ["с", "KGS"],
    flag: "🇰🇬",
    name: "Kyrgyzstani Som",
    decimals: 2,
  },
  KHR: {
    symbol: ["៛", "KHR"],
    flag: "🇰🇭",
    name: "Cambodian Riel",
    decimals: 2,
  },
  KMF: {
    symbol: ["CF", "KMF"],
    flag: "🇰🇲",
    name: "Comorian Franc",
    decimals: 0,
  },
  KPW: {
    symbol: ["₩", "KPW"],
    flag: "🇰🇵",
    name: "North Korean Won",
    decimals: 2,
  },
  KRW: {
    symbol: ["₩", "KRW"],
    flag: "🇰🇷",
    name: "South Korean Won",
    decimals: 0,
  },
  KWD: {
    symbol: ["د.ك", "KWD"],
    flag: "🇰🇼",
    name: "Kuwaiti Dinar",
    decimals: 3,
  },
  KYD: {
    symbol: ["$", "KYD"],
    flag: "🇰🇾",
    name: "Cayman Islands Dollar",
    decimals: 2,
  },
  KZT: {
    symbol: ["₸", "KZT"],
    flag: "🇰🇿",
    name: "Kazakhstani Tenge",
    decimals: 2,
  },
  LAK: { symbol: ["₭", "LAK"], flag: "🇱🇦", name: "Lao Kip", decimals: 2 },
  LBP: {
    symbol: ["ل.ل", "LBP"],
    flag: "🇱🇧",
    name: "Lebanese Pound",
    decimals: 2,
  },
  LKR: {
    symbol: ["Rs", "LKR"],
    flag: "🇱🇰",
    name: "Sri Lankan Rupee",
    decimals: 2,
  },
  LRD: {
    symbol: ["$", "LRD"],
    flag: "🇱🇷",
    name: "Liberian Dollar",
    decimals: 2,
  },
  LSL: { symbol: ["L", "LSL"], flag: "🇱🇸", name: "Lesotho Loti", decimals: 2 },
  LYD: {
    symbol: ["ل.د", "LYD"],
    flag: "🇱🇾",
    name: "Libyan Dinar",
    decimals: 3,
  },
  MAD: {
    symbol: ["د.م.", "MAD"],
    flag: "🇲🇦",
    name: "Moroccan Dirham",
    decimals: 2,
  },
  MDL: { symbol: ["L", "MDL"], flag: "🇲🇩", name: "Moldovan Leu", decimals: 2 },
  MGA: {
    symbol: ["Ar", "MGA"],
    flag: "🇲🇬",
    name: "Malagasy Ariary",
    decimals: 0,
  },
  MKD: {
    symbol: ["ден", "MKD"],
    flag: "🇲🇰",
    name: "Macedonian Denar",
    decimals: 2,
  },
  MMK: { symbol: ["K", "MMK"], flag: "🇲🇲", name: "Myanmar Kyat", decimals: 2 },
  MNT: {
    symbol: ["₮", "MNT"],
    flag: "🇲🇳",
    name: "Mongolian Tögrög",
    decimals: 2,
  },
  MOP: {
    symbol: ["MOP$", "MOP"],
    flag: "🇲🇴",
    name: "Macanese Pataca",
    decimals: 2,
  },
  MRU: {
    symbol: ["UM", "MRU"],
    flag: "🇲🇷",
    name: "Mauritanian Ouguiya",
    decimals: 0,
  },
  MUR: {
    symbol: ["₨", "MUR"],
    flag: "🇲🇺",
    name: "Mauritian Rupee",
    decimals: 2,
  },
  MVR: {
    symbol: ["Rf", "MVR"],
    flag: "🇲🇻",
    name: "Maldivian Rufiyaa",
    decimals: 2,
  },
  MWK: {
    symbol: ["MK", "MWK"],
    flag: "🇲🇼",
    name: "Malawian Kwacha",
    decimals: 2,
  },
  MXN: { symbol: ["$", "MXN"], flag: "🇲🇽", name: "Mexican Peso", decimals: 2 },
  MYR: {
    symbol: ["RM", "MYR"],
    flag: "🇲🇾",
    name: "Malaysian Ringgit",
    decimals: 2,
  },
  MZN: {
    symbol: ["MT", "MZN"],
    flag: "🇲🇿",
    name: "Mozambican Metical",
    decimals: 2,
  },
  NAD: {
    symbol: ["$", "NAD"],
    flag: "🇳🇦",
    name: "Namibian Dollar",
    decimals: 2,
  },
  NGN: {
    symbol: ["₦", "NGN"],
    flag: "🇳🇬",
    name: "Nigerian Naira",
    decimals: 2,
  },
  NIO: {
    symbol: ["C$", "NIO"],
    flag: "🇳🇮",
    name: "Nicaraguan Córdoba",
    decimals: 2,
  },
  NOK: {
    symbol: ["kr", "NOK"],
    flag: "🇳🇴",
    name: "Norwegian Krone",
    decimals: 2,
  },
  NPR: {
    symbol: ["Rs", "NPR"],
    flag: "🇳🇵",
    name: "Nepalese Rupee",
    decimals: 2,
  },
  NZD: {
    symbol: ["NZ$", "NZD"],
    flag: "🇳🇿",
    name: "New Zealand Dollar",
    decimals: 2,
  },
  OMR: { symbol: ["ر.ع.", "OMR"], flag: "🇴🇲", name: "Omani Rial", decimals: 3 },
  PAB: {
    symbol: ["B/.", "PAB"],
    flag: "🇵🇦",
    name: "Panamanian Balboa",
    decimals: 2,
  },
  PEN: { symbol: ["S/", "PEN"], flag: "🇵🇪", name: "Peruvian Sol", decimals: 2 },
  PGK: {
    symbol: ["K", "PGK"],
    flag: "🇵🇬",
    name: "Papua New Guinean Kina",
    decimals: 2,
  },
  PHP: {
    symbol: ["₱", "PHP"],
    flag: "🇵🇭",
    name: "Philippine Peso",
    decimals: 2,
  },
  PKR: {
    symbol: ["Rs", "PKR"],
    flag: "🇵🇰",
    name: "Pakistani Rupee",
    decimals: 2,
  },
  PLN: { symbol: ["zł", "PLN"], flag: "🇵🇱", name: "Polish Złoty", decimals: 2 },
  PYG: {
    symbol: ["₲", "PYG"],
    flag: "🇵🇾",
    name: "Paraguayan Guaraní",
    decimals: 0,
  },
  QAR: {
    symbol: ["ر.ق", "QAR"],
    flag: "🇶🇦",
    name: "Qatari Riyal",
    decimals: 2,
  },
  RON: {
    symbol: ["lei", "RON"],
    flag: "🇷🇴",
    name: "Romanian Leu",
    decimals: 2,
  },
  RSD: {
    symbol: ["дин.", "RSD"],
    flag: "🇷🇸",
    name: "Serbian Dinar",
    decimals: 2,
  },
  RUB: { symbol: ["₽", "RUB"], flag: "🇷🇺", name: "Russian Ruble", decimals: 2 },
  RWF: {
    symbol: ["FRw", "RWF"],
    flag: "🇷🇼",
    name: "Rwandan Franc",
    decimals: 0,
  },
  SAR: { symbol: ["﷼", "SAR"], flag: "🇸🇦", name: "Saudi Riyal", decimals: 2 },
  SBD: {
    symbol: ["$", "SBD"],
    flag: "🇸🇧",
    name: "Solomon Islands Dollar",
    decimals: 2,
  },
  SCR: {
    symbol: ["₨", "SCR"],
    flag: "🇸🇨",
    name: "Seychellois Rupee",
    decimals: 2,
  },
  SDG: {
    symbol: ["ج.س.", "SDG"],
    flag: "🇸🇩",
    name: "Sudanese Pound",
    decimals: 2,
  },
  SEK: {
    symbol: ["kr", "SEK"],
    flag: "🇸🇪",
    name: "Swedish Krona",
    decimals: 2,
  },
  SGD: {
    symbol: ["S$", "SGD"],
    flag: "🇸🇬",
    name: "Singapore Dollar",
    decimals: 2,
  },
  SHP: {
    symbol: ["£", "SHP"],
    flag: "🇸🇭",
    name: "Saint Helenian Pound",
    decimals: 2,
  },
  SLE: {
    symbol: ["Le", "SLE"],
    flag: "🇸🇱",
    name: "Sierra Leonean Leone",
    decimals: 2,
  },
  SOS: {
    symbol: ["S", "SOS"],
    flag: "🇸🇴",
    name: "Somali Shilling",
    decimals: 2,
  },
  SRD: {
    symbol: ["$", "SRD"],
    flag: "🇸🇷",
    name: "Surinamese Dollar",
    decimals: 2,
  },
  SSP: {
    symbol: ["£", "SSP"],
    flag: "🇸🇸",
    name: "South Sudanese Pound",
    decimals: 2,
  },
  STN: {
    symbol: ["Db", "STN"],
    flag: "🇸🇹",
    name: "São Tomé and Príncipe Dobra",
    decimals: 2,
  },
  SVC: {
    symbol: ["$", "SVC"],
    flag: "🇸🇻",
    name: "Salvadoran Colón",
    decimals: 2,
  },
  SYP: { symbol: ["£", "SYP"], flag: "🇸🇾", name: "Syrian Pound", decimals: 2 },
  SZL: {
    symbol: ["L", "SZL"],
    flag: "🇸🇿",
    name: "Swazi Lilangeni",
    decimals: 2,
  },
  THB: { symbol: ["฿", "THB"], flag: "🇹🇭", name: "Thai Baht", decimals: 2 },
  TJS: {
    symbol: ["SM", "TJS"],
    flag: "🇹🇯",
    name: "Tajikistani Somoni",
    decimals: 2,
  },
  TMT: {
    symbol: ["m", "TMT"],
    flag: "🇹🇲",
    name: "Turkmenistani Manat",
    decimals: 2,
  },
  TND: {
    symbol: ["د.ت", "TND"],
    flag: "🇹🇳",
    name: "Tunisian Dinar",
    decimals: 3,
  },
  TOP: {
    symbol: ["T$", "TOP"],
    flag: "🇹🇴",
    name: "Tongan Paʻanga",
    decimals: 2,
  },
  TRY: { symbol: ["₺", "TRY"], flag: "🇹🇷", name: "Turkish Lira", decimals: 2 },
  TTD: {
    symbol: ["$", "TTD"],
    flag: "🇹🇹",
    name: "Trinidad and Tobago Dollar",
    decimals: 2,
  },
  TWD: {
    symbol: ["NT$", "TWD"],
    flag: "🇹🇼",
    name: "New Taiwan Dollar",
    decimals: 2,
  },
  TZS: {
    symbol: ["TSh", "TZS"],
    flag: "🇹🇿",
    name: "Tanzanian Shilling",
    decimals: 2,
  },
  UAH: {
    symbol: ["₴", "UAH"],
    flag: "🇺🇦",
    name: "Ukrainian Hryvnia",
    decimals: 2,
  },
  UGX: {
    symbol: ["USh", "UGX"],
    flag: "🇺🇬",
    name: "Ugandan Shilling",
    decimals: 0,
  },
  USD: { symbol: ["$", "USD"], flag: "🇺🇸", name: "US Dollar", decimals: 2 },
  UYU: {
    symbol: ["$", "UYU"],
    flag: "🇺🇾",
    name: "Uruguayan Peso",
    decimals: 2,
  },
  UZS: {
    symbol: ["so'm", "UZS"],
    flag: "🇺🇿",
    name: "Uzbekistani Som",
    decimals: 2,
  },
  VES: {
    symbol: ["Bs.", "VES"],
    flag: "🇻🇪",
    name: "Venezuelan Bolívar Soberano",
    decimals: 2,
  },
  VND: {
    symbol: ["₫", "VND"],
    flag: "🇻🇳",
    name: "Vietnamese Đồng",
    decimals: 0,
  },
  VUV: { symbol: ["VT", "VUV"], flag: "🇻🇺", name: "Vanuatu Vatu", decimals: 0 },
  WST: { symbol: ["T", "WST"], flag: "🇼🇸", name: "Samoan Tala", decimals: 2 },
  XAF: {
    symbol: ["FCFA", "XAF"],
    flag: "🌍",
    name: "Central African CFA Franc",
    decimals: 0,
  },
  XAG: {
    symbol: ["XAG"],
    flag: "🥈",
    name: "Silver (Troy Ounce)",
    decimals: 2,
  },
  XAU: { symbol: ["XAU"], flag: "🥇", name: "Gold (Troy Ounce)", decimals: 2 },
  XCD: {
    symbol: ["$", "XCD"],
    flag: "🌎",
    name: "East Caribbean Dollar",
    decimals: 2,
  },
  XCG: {
    symbol: ["ƒ", "XCG"],
    flag: "🇨🇼",
    name: "Caribbean Guilder",
    decimals: 2,
  },
  XDR: {
    symbol: ["SDR", "XDR"],
    flag: "🌐",
    name: "Special Drawing Rights",
    decimals: 2,
  },
  XOF: {
    symbol: ["CFA", "XOF"],
    flag: "🌍",
    name: "West African CFA Franc",
    decimals: 0,
  },
  XPD: {
    symbol: ["XPD", "XPD"],
    flag: "⚪",
    name: "Palladium (Troy Ounce)",
    decimals: 2,
  },
  XPF: { symbol: ["₣", "XPF"], flag: "🇵🇫", name: "CFP Franc", decimals: 0 },
  XPT: {
    symbol: ["XPT", "XPT"],
    flag: "⚪",
    name: "Platinum (Troy Ounce)",
    decimals: 2,
  },
  YER: { symbol: ["﷼", "YER"], flag: "🇾🇪", name: "Yemeni Rial", decimals: 2 },
  ZAR: {
    symbol: ["R", "ZAR"],
    flag: "🇿🇦",
    name: "South African Rand",
    decimals: 2,
  },
  ZMW: {
    symbol: ["ZK", "ZMW"],
    flag: "🇿🇲",
    name: "Zambian Kwacha",
    decimals: 2,
  },
  ZWG: {
    symbol: ["ZiG", "ZWG"],
    flag: "🇿🇼",
    name: "Zimbabwe Gold",
    decimals: 2,
  },
};

// Symbol → shortcode for price detection on web pages
// (only symbols that are visually unique to one currency are included here —
// shared/ambiguous symbols like "kr", "Rs", "L", or "$" variants beyond the
// ones below are left out to avoid false-positive matches)
const CURRENCY_SYMBOLS = {
  $: ["USD"],
  "€": ["EUR"],
  "£": ["GBP"],
  "¥": ["JPY"],
  "₹": ["INR"],
  "₩": ["KRW"],
  A$: ["AUD"],
  C$: ["CAD"],
  S$: ["SGD"],
  "৳": ["BDT"],
  NZ$: ["NZD"],
  HK$: ["HKD"],
  R$: ["BRL"],
  "₴": ["UAH"],
  "₺": ["TRY"],
  "₦": ["NGN"],
  "₪": ["ILS"],
  "₫": ["VND"],
  "₽": ["RUB"],
  "₱": ["PHP"],
  "₭": ["LAK"],
  "₮": ["MNT"],
  "฿": ["THB"],
  "₡": ["CRC"],
  "₲": ["PYG"],
  "₼": ["AZN"],
  "₾": ["GEL"],
  "֏": ["AMD"],
  "₸": ["KZT"],
  "₵": ["GHS"],
  "؋": ["AFN"],
  "៛": ["KHR"],
  zł: ["PLN"],
};

globalThis.CURRENCIES = CURRENCIES;
globalThis.CURRENCY_SYMBOLS = CURRENCY_SYMBOLS;
