// Shared currency dictionary — shortcode → metadata
const CURRENCIES = {
  AED: { symbol: "د.إ", flag: "🇦🇪", name: "UAE Dirham", decimals: 2 },
  AFN: { symbol: "؋", flag: "🇦🇫", name: "Afghan Afghani", decimals: 2 },
  ALL: { symbol: "L", flag: "🇦🇱", name: "Albanian Lek", decimals: 2 },
  AMD: { symbol: "֏", flag: "🇦🇲", name: "Armenian Dram", decimals: 2 },
  ANG: {
    symbol: "ƒ",
    flag: "🇨🇼",
    name: "Netherlands Antillean Guilder",
    decimals: 2,
  },
  AOA: { symbol: "Kz", flag: "🇦🇴", name: "Angolan Kwanza", decimals: 2 },
  ARS: { symbol: "$", flag: "🇦🇷", name: "Argentine Peso", decimals: 2 },
  AUD: { symbol: "A$", flag: "🇦🇺", name: "Australian Dollar", decimals: 2 },
  AWG: { symbol: "ƒ", flag: "🇦🇼", name: "Aruban Florin", decimals: 2 },
  AZN: { symbol: "₼", flag: "🇦🇿", name: "Azerbaijani Manat", decimals: 2 },
  BAM: {
    symbol: "KM",
    flag: "🇧🇦",
    name: "Bosnia-Herzegovina Convertible Mark",
    decimals: 2,
  },
  BBD: { symbol: "$", flag: "🇧🇧", name: "Barbadian Dollar", decimals: 2 },
  BDT: { symbol: "৳", flag: "🇧🇩", name: "Bangladeshi Taka", decimals: 0 },
  BHD: { symbol: "د.ب", flag: "🇧🇭", name: "Bahraini Dinar", decimals: 3 },
  BIF: { symbol: "FBu", flag: "🇧🇮", name: "Burundian Franc", decimals: 0 },
  BMD: { symbol: "$", flag: "🇧🇲", name: "Bermudian Dollar", decimals: 2 },
  BND: { symbol: "$", flag: "🇧🇳", name: "Brunei Dollar", decimals: 2 },
  BOB: { symbol: "Bs.", flag: "🇧🇴", name: "Bolivian Boliviano", decimals: 2 },
  BRL: { symbol: "R$", flag: "🇧🇷", name: "Brazilian Real", decimals: 2 },
  BSD: { symbol: "$", flag: "🇧🇸", name: "Bahamian Dollar", decimals: 2 },
  BTN: { symbol: "Nu.", flag: "🇧🇹", name: "Bhutanese Ngultrum", decimals: 2 },
  BWP: { symbol: "P", flag: "🇧🇼", name: "Botswana Pula", decimals: 2 },
  BYN: { symbol: "Br", flag: "🇧🇾", name: "Belarusian Ruble", decimals: 2 },
  BZD: { symbol: "$", flag: "🇧🇿", name: "Belize Dollar", decimals: 2 },
  CAD: { symbol: "C$", flag: "🇨🇦", name: "Canadian Dollar", decimals: 2 },
  CDF: { symbol: "FC", flag: "🇨🇩", name: "Congolese Franc", decimals: 2 },
  CHF: { symbol: "CHF", flag: "🇨🇭", name: "Swiss Franc", decimals: 2 },
  CLP: { symbol: "$", flag: "🇨🇱", name: "Chilean Peso", decimals: 0 },
  CNH: {
    symbol: "¥",
    flag: "🇨🇳",
    name: "Chinese Yuan (Offshore)",
    decimals: 2,
  },
  CNY: { symbol: "¥", flag: "🇨🇳", name: "Chinese Yuan Renminbi", decimals: 2 },
  COP: { symbol: "$", flag: "🇨🇴", name: "Colombian Peso", decimals: 2 },
  CRC: { symbol: "₡", flag: "🇨🇷", name: "Costa Rican Colón", decimals: 2 },
  CUP: { symbol: "$", flag: "🇨🇺", name: "Cuban Peso", decimals: 2 },
  CVE: { symbol: "$", flag: "🇨🇻", name: "Cape Verdean Escudo", decimals: 2 },
  CZK: { symbol: "Kč", flag: "🇨🇿", name: "Czech Koruna", decimals: 2 },
  DJF: { symbol: "Fdj", flag: "🇩🇯", name: "Djiboutian Franc", decimals: 0 },
  DKK: { symbol: "kr", flag: "🇩🇰", name: "Danish Krone", decimals: 2 },
  DOP: { symbol: "$", flag: "🇩🇴", name: "Dominican Peso", decimals: 2 },
  DZD: { symbol: "د.ج", flag: "🇩🇿", name: "Algerian Dinar", decimals: 2 },
  EGP: { symbol: "£", flag: "🇪🇬", name: "Egyptian Pound", decimals: 2 },
  ERN: { symbol: "Nfk", flag: "🇪🇷", name: "Eritrean Nakfa", decimals: 2 },
  ETB: { symbol: "Br", flag: "🇪🇹", name: "Ethiopian Birr", decimals: 2 },
  EUR: { symbol: "€", flag: "🇪🇺", name: "Euro", decimals: 2 },
  FJD: { symbol: "$", flag: "🇫🇯", name: "Fijian Dollar", decimals: 2 },
  FKP: { symbol: "£", flag: "🇫🇰", name: "Falkland Islands Pound", decimals: 2 },
  GBP: { symbol: "£", flag: "🇬🇧", name: "British Pound", decimals: 2 },
  GEL: { symbol: "₾", flag: "🇬🇪", name: "Georgian Lari", decimals: 2 },
  GGP: { symbol: "£", flag: "🇬🇬", name: "Guernsey Pound", decimals: 2 },
  GHS: { symbol: "₵", flag: "🇬🇭", name: "Ghanaian Cedi", decimals: 2 },
  GIP: { symbol: "£", flag: "🇬🇮", name: "Gibraltar Pound", decimals: 2 },
  GMD: { symbol: "D", flag: "🇬🇲", name: "Gambian Dalasi", decimals: 2 },
  GNF: { symbol: "FG", flag: "🇬🇳", name: "Guinean Franc", decimals: 0 },
  GTQ: { symbol: "Q", flag: "🇬🇹", name: "Guatemalan Quetzal", decimals: 2 },
  GYD: { symbol: "$", flag: "🇬🇾", name: "Guyanese Dollar", decimals: 2 },
  HKD: { symbol: "$", flag: "🇭🇰", name: "Hong Kong Dollar", decimals: 2 },
  HNL: { symbol: "L", flag: "🇭🇳", name: "Honduran Lempira", decimals: 2 },
  HTG: { symbol: "G", flag: "🇭🇹", name: "Haitian Gourde", decimals: 2 },
  HUF: { symbol: "Ft", flag: "🇭🇺", name: "Hungarian Forint", decimals: 2 },
  IDR: { symbol: "Rp", flag: "🇮🇩", name: "Indonesian Rupiah", decimals: 2 },
  ILS: { symbol: "₪", flag: "🇮🇱", name: "Israeli New Shekel", decimals: 2 },
  IMP: { symbol: "£", flag: "🇮🇲", name: "Isle of Man Pound", decimals: 2 },
  INR: { symbol: "₹", flag: "🇮🇳", name: "Indian Rupee", decimals: 0 },
  IQD: { symbol: "ع.د", flag: "🇮🇶", name: "Iraqi Dinar", decimals: 3 },
  IRR: { symbol: "﷼", flag: "🇮🇷", name: "Iranian Rial", decimals: 2 },
  ISK: { symbol: "kr", flag: "🇮🇸", name: "Icelandic Króna", decimals: 0 },
  JEP: { symbol: "£", flag: "🇯🇪", name: "Jersey Pound", decimals: 2 },
  JMD: { symbol: "$", flag: "🇯🇲", name: "Jamaican Dollar", decimals: 2 },
  JOD: { symbol: "د.ا", flag: "🇯🇴", name: "Jordanian Dinar", decimals: 3 },
  JPY: { symbol: "¥", flag: "🇯🇵", name: "Japanese Yen", decimals: 0 },
  KES: { symbol: "KSh", flag: "🇰🇪", name: "Kenyan Shilling", decimals: 2 },
  KGS: { symbol: "с", flag: "🇰🇬", name: "Kyrgyzstani Som", decimals: 2 },
  KHR: { symbol: "៛", flag: "🇰🇭", name: "Cambodian Riel", decimals: 2 },
  KMF: { symbol: "CF", flag: "🇰🇲", name: "Comorian Franc", decimals: 0 },
  KPW: { symbol: "₩", flag: "🇰🇵", name: "North Korean Won", decimals: 2 },
  KRW: { symbol: "₩", flag: "🇰🇷", name: "South Korean Won", decimals: 0 },
  KWD: { symbol: "د.ك", flag: "🇰🇼", name: "Kuwaiti Dinar", decimals: 3 },
  KYD: { symbol: "$", flag: "🇰🇾", name: "Cayman Islands Dollar", decimals: 2 },
  KZT: { symbol: "₸", flag: "🇰🇿", name: "Kazakhstani Tenge", decimals: 2 },
  LAK: { symbol: "₭", flag: "🇱🇦", name: "Lao Kip", decimals: 2 },
  LBP: { symbol: "ل.ل", flag: "🇱🇧", name: "Lebanese Pound", decimals: 2 },
  LKR: { symbol: "Rs", flag: "🇱🇰", name: "Sri Lankan Rupee", decimals: 2 },
  LRD: { symbol: "$", flag: "🇱🇷", name: "Liberian Dollar", decimals: 2 },
  LSL: { symbol: "L", flag: "🇱🇸", name: "Lesotho Loti", decimals: 2 },
  LYD: { symbol: "ل.د", flag: "🇱🇾", name: "Libyan Dinar", decimals: 3 },
  MAD: { symbol: "د.م.", flag: "🇲🇦", name: "Moroccan Dirham", decimals: 2 },
  MDL: { symbol: "L", flag: "🇲🇩", name: "Moldovan Leu", decimals: 2 },
  MGA: { symbol: "Ar", flag: "🇲🇬", name: "Malagasy Ariary", decimals: 0 },
  MKD: { symbol: "ден", flag: "🇲🇰", name: "Macedonian Denar", decimals: 2 },
  MMK: { symbol: "K", flag: "🇲🇲", name: "Myanmar Kyat", decimals: 2 },
  MNT: { symbol: "₮", flag: "🇲🇳", name: "Mongolian Tögrög", decimals: 2 },
  MOP: { symbol: "MOP$", flag: "🇲🇴", name: "Macanese Pataca", decimals: 2 },
  MRU: { symbol: "UM", flag: "🇲🇷", name: "Mauritanian Ouguiya", decimals: 0 },
  MUR: { symbol: "₨", flag: "🇲🇺", name: "Mauritian Rupee", decimals: 2 },
  MVR: { symbol: "Rf", flag: "🇲🇻", name: "Maldivian Rufiyaa", decimals: 2 },
  MWK: { symbol: "MK", flag: "🇲🇼", name: "Malawian Kwacha", decimals: 2 },
  MXN: { symbol: "$", flag: "🇲🇽", name: "Mexican Peso", decimals: 2 },
  MYR: { symbol: "RM", flag: "🇲🇾", name: "Malaysian Ringgit", decimals: 2 },
  MZN: { symbol: "MT", flag: "🇲🇿", name: "Mozambican Metical", decimals: 2 },
  NAD: { symbol: "$", flag: "🇳🇦", name: "Namibian Dollar", decimals: 2 },
  NGN: { symbol: "₦", flag: "🇳🇬", name: "Nigerian Naira", decimals: 2 },
  NIO: { symbol: "C$", flag: "🇳🇮", name: "Nicaraguan Córdoba", decimals: 2 },
  NOK: { symbol: "kr", flag: "🇳🇴", name: "Norwegian Krone", decimals: 2 },
  NPR: { symbol: "Rs", flag: "🇳🇵", name: "Nepalese Rupee", decimals: 2 },
  NZD: { symbol: "$", flag: "🇳🇿", name: "New Zealand Dollar", decimals: 2 },
  OMR: { symbol: "ر.ع.", flag: "🇴🇲", name: "Omani Rial", decimals: 3 },
  PAB: { symbol: "B/.", flag: "🇵🇦", name: "Panamanian Balboa", decimals: 2 },
  PEN: { symbol: "S/", flag: "🇵🇪", name: "Peruvian Sol", decimals: 2 },
  PGK: { symbol: "K", flag: "🇵🇬", name: "Papua New Guinean Kina", decimals: 2 },
  PHP: { symbol: "₱", flag: "🇵🇭", name: "Philippine Peso", decimals: 2 },
  PKR: { symbol: "Rs", flag: "🇵🇰", name: "Pakistani Rupee", decimals: 2 },
  PLN: { symbol: "zł", flag: "🇵🇱", name: "Polish Złoty", decimals: 2 },
  PYG: { symbol: "₲", flag: "🇵🇾", name: "Paraguayan Guaraní", decimals: 0 },
  QAR: { symbol: "ر.ق", flag: "🇶🇦", name: "Qatari Riyal", decimals: 2 },
  RON: { symbol: "lei", flag: "🇷🇴", name: "Romanian Leu", decimals: 2 },
  RSD: { symbol: "дин.", flag: "🇷🇸", name: "Serbian Dinar", decimals: 2 },
  RUB: { symbol: "₽", flag: "🇷🇺", name: "Russian Ruble", decimals: 2 },
  RWF: { symbol: "FRw", flag: "🇷🇼", name: "Rwandan Franc", decimals: 0 },
  SAR: { symbol: "﷼", flag: "🇸🇦", name: "Saudi Riyal", decimals: 2 },
  SBD: { symbol: "$", flag: "🇸🇧", name: "Solomon Islands Dollar", decimals: 2 },
  SCR: { symbol: "₨", flag: "🇸🇨", name: "Seychellois Rupee", decimals: 2 },
  SDG: { symbol: "ج.س.", flag: "🇸🇩", name: "Sudanese Pound", decimals: 2 },
  SEK: { symbol: "kr", flag: "🇸🇪", name: "Swedish Krona", decimals: 2 },
  SGD: { symbol: "S$", flag: "🇸🇬", name: "Singapore Dollar", decimals: 2 },
  SHP: { symbol: "£", flag: "🇸🇭", name: "Saint Helenian Pound", decimals: 2 },
  SLE: { symbol: "Le", flag: "🇸🇱", name: "Sierra Leonean Leone", decimals: 2 },
  SOS: { symbol: "S", flag: "🇸🇴", name: "Somali Shilling", decimals: 2 },
  SRD: { symbol: "$", flag: "🇸🇷", name: "Surinamese Dollar", decimals: 2 },
  SSP: { symbol: "£", flag: "🇸🇸", name: "South Sudanese Pound", decimals: 2 },
  STN: {
    symbol: "Db",
    flag: "🇸🇹",
    name: "São Tomé and Príncipe Dobra",
    decimals: 2,
  },
  SVC: { symbol: "$", flag: "🇸🇻", name: "Salvadoran Colón", decimals: 2 },
  SYP: { symbol: "£", flag: "🇸🇾", name: "Syrian Pound", decimals: 2 },
  SZL: { symbol: "L", flag: "🇸🇿", name: "Swazi Lilangeni", decimals: 2 },
  THB: { symbol: "฿", flag: "🇹🇭", name: "Thai Baht", decimals: 2 },
  TJS: { symbol: "SM", flag: "🇹🇯", name: "Tajikistani Somoni", decimals: 2 },
  TMT: { symbol: "m", flag: "🇹🇲", name: "Turkmenistani Manat", decimals: 2 },
  TND: { symbol: "د.ت", flag: "🇹🇳", name: "Tunisian Dinar", decimals: 3 },
  TOP: { symbol: "T$", flag: "🇹🇴", name: "Tongan Paʻanga", decimals: 2 },
  TRY: { symbol: "₺", flag: "🇹🇷", name: "Turkish Lira", decimals: 2 },
  TTD: {
    symbol: "$",
    flag: "🇹🇹",
    name: "Trinidad and Tobago Dollar",
    decimals: 2,
  },
  TWD: { symbol: "NT$", flag: "🇹🇼", name: "New Taiwan Dollar", decimals: 2 },
  TZS: { symbol: "TSh", flag: "🇹🇿", name: "Tanzanian Shilling", decimals: 2 },
  UAH: { symbol: "₴", flag: "🇺🇦", name: "Ukrainian Hryvnia", decimals: 2 },
  UGX: { symbol: "USh", flag: "🇺🇬", name: "Ugandan Shilling", decimals: 0 },
  USD: { symbol: "$", flag: "🇺🇸", name: "US Dollar", decimals: 2 },
  UYU: { symbol: "$", flag: "🇺🇾", name: "Uruguayan Peso", decimals: 2 },
  UZS: { symbol: "so'm", flag: "🇺🇿", name: "Uzbekistani Som", decimals: 2 },
  VES: {
    symbol: "Bs.",
    flag: "🇻🇪",
    name: "Venezuelan Bolívar Soberano",
    decimals: 2,
  },
  VND: { symbol: "₫", flag: "🇻🇳", name: "Vietnamese Đồng", decimals: 0 },
  VUV: { symbol: "VT", flag: "🇻🇺", name: "Vanuatu Vatu", decimals: 0 },
  WST: { symbol: "T", flag: "🇼🇸", name: "Samoan Tala", decimals: 2 },
  XAF: {
    symbol: "FCFA",
    flag: "🌍",
    name: "Central African CFA Franc",
    decimals: 0,
  },
  XAG: { symbol: "XAG", flag: "🥈", name: "Silver (Troy Ounce)", decimals: 2 },
  XAU: { symbol: "XAU", flag: "🥇", name: "Gold (Troy Ounce)", decimals: 2 },
  XCD: { symbol: "$", flag: "🌎", name: "East Caribbean Dollar", decimals: 2 },
  XCG: { symbol: "ƒ", flag: "🇨🇼", name: "Caribbean Guilder", decimals: 2 },
  XDR: {
    symbol: "SDR",
    flag: "🌐",
    name: "Special Drawing Rights",
    decimals: 2,
  },
  XOF: {
    symbol: "CFA",
    flag: "🌍",
    name: "West African CFA Franc",
    decimals: 0,
  },
  XPD: {
    symbol: "XPD",
    flag: "⚪",
    name: "Palladium (Troy Ounce)",
    decimals: 2,
  },
  XPF: { symbol: "₣", flag: "🇵🇫", name: "CFP Franc", decimals: 0 },
  XPT: {
    symbol: "XPT",
    flag: "⚪",
    name: "Platinum (Troy Ounce)",
    decimals: 2,
  },
  YER: { symbol: "﷼", flag: "🇾🇪", name: "Yemeni Rial", decimals: 2 },
  ZAR: { symbol: "R", flag: "🇿🇦", name: "South African Rand", decimals: 2 },
  ZMW: { symbol: "ZK", flag: "🇿🇲", name: "Zambian Kwacha", decimals: 2 },
  ZWG: { symbol: "ZiG", flag: "🇿🇼", name: "Zimbabwe Gold", decimals: 2 },
};

// Symbol → shortcode for price detection on web pages
// (only symbols that are visually unique to one currency are included here —
// shared/ambiguous symbols like "kr", "Rs", "L", or "$" variants beyond the
// ones below are left out to avoid false-positive matches)
const CURRENCY_SYMBOLS = {
  $: "USD",
  "€": "EUR",
  "£": "GBP",
  "¥": "JPY",
  "₹": "INR",
  "₩": "KRW",
  A$: "AUD",
  C$: "CAD",
  S$: "SGD",
  "৳": "BDT",
  NZ$: "NZD",
  HK$: "HKD",
  R$: "BRL",
  "₴": "UAH",
  "₺": "TRY",
  "₦": "NGN",
  "₪": "ILS",
  "₫": "VND",
  "₽": "RUB",
  "₱": "PHP",
  "₭": "LAK",
  "₮": "MNT",
  "฿": "THB",
  "₡": "CRC",
  "₲": "PYG",
  "₼": "AZN",
  "₾": "GEL",
  "֏": "AMD",
  "₸": "KZT",
  "₵": "GHS",
  "؋": "AFN",
  "៛": "KHR",
  zł: "PLN",
};

globalThis.CURRENCIES = CURRENCIES;
globalThis.CURRENCY_SYMBOLS = CURRENCY_SYMBOLS;
